config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :customers, controllers: {
    sessions:      'publics/sessions',
    passwords:     'publics/passwords',
    registrations: 'publics/registrations'
  }

  scope module: :publics do
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/my_page' => 'customers#show'
    resources :customers, only: [:edit, :update]
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources :items, only: [:index, :show, :create]
    resources :carts, only: [:index, :update, :destroy, :create]
    delete 'cart/destroy_all' => 'carts#destroy_all'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :show, :new, :create]
    get 'about' => 'homes#about'
    resources :addresses, only: [:index, :create, :edit, :destroy, :update]
  end

  namespace :admins do
    resources :items
    resources :genres, only: [:index, :new, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index]
  end

  root 'homes#top'
end

app/models/order.rb
class Order < ApplicationRecord
  enum pay_way: { "クレジットカード": 0, "銀行振込": 1 }
  has_many :order_details, dependent: :destroy
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  
  def index 
    @orders = Order
  end 
  
end

app/controllers/publics/addresses_controller.rb
class Publics::AddressesController < ApplicationController

  def index
    @address = Address.new
    @addresses = Address.all
    @customer = current_customer
  end

  def create
    address = Address.new(address_params)
    address.customer_id = current_customer.id
    address.save
    redirect_to addresses_path
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    address = Address.find(params[:id])
    address.update(address_params)
    redirect_to addresses_path
  end

  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to addresses_path
  end

  private
  def address_params
    params.require(:address).permit(:postcode, :address, :name)
  end

end

app/controllers/publics/carts_controller.rb
class Publics::CartsController < ApplicationController

  def index
    @customer = current_customer
    @carts = @customer.carts.all
    @cart = current_customer.carts.find_by(item_id: params[:item_id])
    @total = 0
  end

  def create
    @customer = current_customer
    if Cart.exists?(item_id: @item, customer_id: @customer)
      @cart = Cart.find_by(item_id: @item.id, customer_id: @customer)
      @cart.amount += params[:cart][:amount].to_i
      @cart.update(amount: @cart.amount)
      redirect_to carts_path
    else
      @cart = Cart.new(cart_params)
      @cart.customer_id = current_customer.id
      if @cart.save
        redirect_to carts_path
      else
        flash[:cart] = "カートに入れる個数を入力してください"
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.update(cart_params)
    if @cart.amount == 0
      @cart.destroy
    end
    redirect_to carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy 
    redirect_to carts_path 
  end

  def destroy_all
    current_customer.carts.destroy_all 
    redirect_to carts_path 
  end

  private
  def cart_params
    params.require(:cart).permit(:item_id, :customer_id, :amount)
  end

end

app/controllers/publics/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/publics/customers_controller.rb
class Publics::CustomersController < ApplicationController

  def show
    @customer = current_customer
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to edit_customer_path
  end

  def unsubscribe
    @customer = current_customer
  end

  def withdraw
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :address, :phonenumber, :withdraw)
  end

end

app/controllers/publics/items_controller.rb
class Publics::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @cart = Cart.new
      if @cart.amount == '個数選択'
        redirect_to item_path(item)
      end
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :is_status)
  end

end

app/controllers/publics/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/publics/orders_controller.rb
class Publics::OrdersController < ApplicationController

  def index
     @orders = Order.where(customer_id: current_customer.id)
     @total = 0
  end

  def show
  end

  def new
    @order = Order.new
    @customer = current_customer
    @addresses = @customer.addresses
  end

  def create
    @order = Order.new(order_params)
    @order.save
    redirect_to orders_complete_path
    @customer = current_customer
    @carts = @customer.carts.all
    @carts.each do |cart|
      @order_detail = OrderDetail.new
      @order_detail.item_id = cart.item_id
      @order_detail.price = cart.item.price
      @order_detail.amount = cart.amount
      @order_detail.order_id = @order.id
      @order_detail.save
    end
    current_customer.carts.destroy_all
  end

  def confirm
    @order = Order.new(order_params)
    @customer = current_customer
    @carts = @customer.carts.all

    if params[:order][:order] == "0"
      @order.postcode = @customer.postcode
      @order.address = @customer.address
      @order.name = @customer.last_name + @customer.first_name
    elsif params[:order][:order] == "1"
      @address = Address.find(params[:order][:id])
      @order.postcode = @address.postcode
      @order.address = @address.address
      @order.name = @address.name
    else
      @order.postcode = params[:order][:postcode]
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
      Adress.create!(customer_id: @customer.id, postcode: @order.postcode, address: @order.address, name: @order.name)
    end

  end

  def complete
  end

  private
  def order_params
    params.require(:order).permit(:customer_id, :shipping_cost, :pay_way, :name, :postcode, :address)
  end

end

app/controllers/publics/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/publics/registrations_controller.rb
# frozen_string_literal: true

class Publics::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/publics/sessions_controller.rb
# frozen_string_literal: true

class Publics::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/publics/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/publics/orders/complete.html.erb
<h4 class="complete">
  ご注文ありがとうございました！！
</h4>

app/views/publics/orders/confirm.html.erb
<h4>注文情報確認</h4>
<table>
  <tr>
    <th>商品名</th>
    <th>単価(税込)</th>
    <th>数量</th>
    <th>小計</th>
  </tr>
  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td>
          <%= cart.item.name %>
        </td>
        <td>
          <%= cart.item.price %>
        </td>
        <td>
          <%= cart.amount.to_i %>
        </td>
         <td>
          <%= cart.item.price * cart.amount.to_i %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <tbody>
    <tr>
      <th>送料</th>
      <td>800</td>
    </tr>
    <tr>
      <th>商品合計</th>
      <td>
        <% total_price = 0 %>
        <% @carts.each do |cart| %>
          <% one_item = cart.item.price * cart.amount %>
          <% total_price += one_item %>
        <% end %>
        <%= total_price %>
      </td>
    </tr>
    <tr>
      <th>請求金額</th>
      <td><%= total_price + 800 %></td>
    </tr>
  </tbody>
</table>

<p>支払方法</p>
<%= @order.pay_way %>

<p>お届け先</p>
<%= @order.postcode + "" + @order.address + "" + @order.name %>

<%= form_with model: @order, url: orders_path, local: true do |f| %>
  <%= f.hidden_field :customer_id, value: current_customer.id %>
  <%= f.hidden_field :pay_way, value: @order.pay_way %>
  <%= f.hidden_field :postcode, value: @order.postcode %>
  <%= f.hidden_field :address, value: @order.address %>
  <%= f.hidden_field :name, value: @order.name %>
  <%= f.submit "注文を確定する" %>
<% end %>

app/views/publics/orders/index.html.erb
<h4>注文履歴一覧</h4>

<table>
  <tr>
    <th>注文日</th>
    <th>配送先</th>
    <th>注文商品</th>
    <th>支払金額</th>
    <th>ステータス</th>
    <th>注文詳細</th>
  </tr>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td>
          <%= order.created_at.strftime('%Y/%m/%d') %>
        </td>
        <td>
          <%= order.postcode %>
          <%= order.address %>
          <%= order.name %>
        </td>
        <td>
          <% order.order_details.each do |detail| %>
            <%= detail.item.name %>
          <% end %>
        </td>
        <td>
          <% order.order_details.each do |order_detail| %> 
            <% sub_total = (order_detail.item.price.*1.1 * order_detail.amount) %>
            <% @total = sub_total %>
          <% end %>
          <%= (@total + 800).round.to_s(:delimited) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/publics/orders/new.html.erb
<h4>注文情報入力</h4>

<%= form_with model: @order, url: orders_confirm_path, local: true do |f| %>
  <div>
    <p>注文方法</p>
    <div>
      <%= f.radio_button :pay_way, "クレジットカード", checked: true  %>クレジットカード
    </div>
    <div>
      <%= f.radio_button :pay_way, "銀行振込" %>銀行振込
    </div>
  </div>

  <div>
    <p>お届け先</p>
    <div>
      <div><%= f.radio_button :order, 0, checked: true  %>ご自身の住所</div>
      <div><%= @customer.postcode + @customer.address %></div>
      <div><%= @customer.last_name + @customer.first_name %></div>
    </div>
    <div>
      <div><%= f.radio_button :order, 1 %>登録済住所から選択</div>
      <%= f.collection_select(:id, @addresses, :id, :register_address )%>
    </div>
    <div>
      <%= f.radio_button :order, 2 %>新しいお届け先
      <div>
        <%= f.label :"郵便番号(ハイフンなし)" %>
        <%= f.text_field :postcode %>
      </div>
      <div>
        <%= f.label :"住所" %>
        <%= f.text_field :address %>
      </div>
      <div>
        <%= f.label :"宛名" %>
        <%= f.text_field :name %>
      </div>
    </div>
    <%= f.submit "確認画面へ進む" %>
  </div>
<% end %>

app/views/publics/orders/show.html.erb
<h4>ここはShow</h4>