config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :customers, controllers: {
    sessions:      'publics/sessions',
    passwords:     'publics/passwords',
    registrations: 'publics/registrations'
  }

  scope module: :publics do
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/my_page' => 'customers#show'
    resources :customers, only: [:edit, :update]
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources :items, only: [:index, :show, :create]
    resources :carts, only: [:index, :update, :destroy, :create]
    delete 'cart/destroy_all' => 'carts#destroy_all'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :show, :new, :create]
    get 'about' => 'homes#about'
    resources :addresses, only: [:index, :create, :edit, :destroy, :update]
  end

  namespace :admins do
    resources :items
    resources :genres, only: [:index, :new, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index]
  end

  root 'homes#top'
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def register_address
    postcode + " " + " " + address + " " + " "+ name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carts, dependent: :destroy
  has_many :addresses, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  attachment :image
  belongs_to :genre
  has_many :carts, dependent: :destroy
  has_many :order_details, dependent: :destroy

end

app/models/order.rb
class Order < ApplicationRecord
  enum pay_way: { "クレジットカード": 0, "銀行振込": 1 }
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admins_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to  admins_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admins_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admins_items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :genre_id)
  end

end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  
  def index 
    @orders = Order
  end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # ログイン、ログアウト先の設定
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admins_items_path
    when Customer
      items_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == Admin
      admins_sign_in_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :address, :phonenumber])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @items = Item.all
  end

end

app/controllers/publics/carts_controller.rb
class Publics::CartsController < ApplicationController

  def index
    @customer = current_customer
    @carts = @customer.carts.all
    @cart = current_customer.carts.find_by(item_id: params[:item_id])
    @total = 0
  end

  def create
    @customer = current_customer
    if Cart.exists?(item_id: @item, customer_id: @customer)
      @cart = Cart.find_by(item_id: @item.id, customer_id: @customer)
      @cart.amount += params[:cart][:amount].to_i
      @cart.update(amount: @cart.amount)
      redirect_to carts_path
    else
      @cart = Cart.new(cart_params)
      @cart.customer_id = current_customer.id
      if @cart.save
        redirect_to carts_path
      else
        flash[:cart] = "カートに入れる個数を入力してください"
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.update(cart_params)
    if @cart.amount == 0
      @cart.destroy
    end
    redirect_to carts_path
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy 
    redirect_to carts_path 
  end

  def destroy_all
    current_customer.carts.destroy_all 
    redirect_to carts_path 
  end

  private
  def cart_params
    params.require(:cart).permit(:item_id, :customer_id, :amount)
  end

end

app/controllers/publics/items_controller.rb
class Publics::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @cart = Cart.new
      if @cart.amount == '個数選択'
        redirect_to item_path(item)
      end
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :is_status)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/items/edit.html.erb
<h4>商品編集</h4>

<%= form_with model: @item, url: admins_item_path, local:true do |f| %>
  <div>
    <label>商品画像</label>
    <%= f.attachment_field :image %>
  </div>

  <div>
    <label>商品名</label>
    <%= f.text_field :name %>
  </div>

  <div>
    <label>商品説明</label>
    <%= f.text_area :explanation %>
  </div>

  <div>
    <label>ジャンル</label>
    <%= f.collection_select(:genre_id, @genres, :id, :name ) %>
  </div>

  <div>
    <label>税抜価格</label>
    <%= f.text_field :price %>
  </div>

  <div>
    <label>販売ステータス</label>
  </div>

  <%= f.submit "変更を保存" %>
<% end %>

app/views/admins/items/index.html.erb
<h4>商品一覧</h4>
<%= link_to "商品追加", new_admins_item_path %>

<table>
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admins_item_path(item) %></td>
        <td><%= item.price %></td>
        <td><%= item.name %></td>
        <td>サンプル</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/items/new.html.erb
<h4>商品新規登録</h4>

<%= form_with model: @item, url: admins_items_path, local:true do |f| %>
  <div>
    <label>商品画像</label>
    <%= f.attachment_field :image %>
  </div>

  <div>
    <label>商品名</label>
    <%= f.text_field :name %>
  </div>

  <div>
    <label>商品説明</label>
    <%= f.text_area :explanation %>
  </div>

  <div>
    <label>ジャンル</label>
    <%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "選択してください"} ) %>
  </div>

  <div>
    <label>税抜価格</label>
    <%= f.text_field :price %>
  </div>

  <div>
    <label>販売ステータス</label>
  </div>

  <%= f.submit "新規登録" %>
<% end %>

app/views/admins/items/show.html.erb
<h4>商品詳細</h4>

<div>
  <p>商品名</p>
  <%= @item.name %>

  <p>商品説明</p>
  <%= @item.explanation %>

  <p>ジャンル</p>
  <%= @item.genre %>

  <p>商品説明</p>
  <%= @item.price %>

  <p>販売ステータス</p>

  <%= link_to "編集する", edit_admins_item_path %>

</div>