config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :customers, controllers: {
    sessions:      'publics/sessions',
    passwords:     'publics/passwords',
    registrations: 'publics/registrations'
  }

  scope module: :publics do
    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/my_page' => 'customers#show'
    resources :customers, only: [:edit, :update]
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    resources :items, only: [:index, :show, :create]
    resources :carts, only: [:index, :update, :destroy, :create]
    delete 'cart/destroy_all' => 'carts#destroy_all'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :show, :new, :create]
    get 'about' => 'homes#about'
    resources :addresses, only: [:index, :create, :edit, :destroy, :update]
  end

  namespace :admins do
    resources :items
    resources :genres, only: [:index, :new, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index]
  end

  root 'homes#top'
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def register_address
    postcode + " " + " " + address + " " + " "+ name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :carts, dependent: :destroy
  has_many :addresses, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  attachment :image
  belongs_to :genre
  has_many :carts, dependent: :destroy
  has_many :order_details, dependent: :destroy

end

app/models/order.rb
class Order < ApplicationRecord
  enum pay_way: { "クレジットカード": 0, "銀行振込": 1 }
  has_many :order_details, dependent: :destroy
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admins_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admins_items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # ログイン、ログアウト先の設定
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admins_items_path
    when Customer
      items_path
    end
  end

  def after_sign_out_path_for(resource)
    if resource == Admin
      admins_sign_in_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :address, :phonenumber])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @items = Item.all
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CakeShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="customer-header">
        <div class="customer-header-nav">
          <%= link_to "LOGO", root_path %>
        </div>
        <% if customer_signed_in? %>
          <div class="customer-header-nav">
            <%= link_to "マイページ", customers_my_page_path %>
          </div>
          <div class="customer-header-nav">
            <%= link_to "商品一覧", items_path %>
          </div>
          <div class="customer-header-nav">
            <%= link_to "カート", carts_path %>
          </div>
          <div class="customer-header-nav">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
          </div>
        <% elsif admin_signed_in? %>
          <div class="customer-header-nav">
            <%= link_to "商品一覧", admins_items_path %>
          </div>
          <div class="customer-header-nav">
            <%= link_to "会員一覧", admins_customers_path %>
          </div>
          <div class="customer-header-nav">
            <%= link_to "注文履歴一覧", admins_orders_path %>
          </div>
          <div class="customer-header-nav">
            <%= link_to "ジャンル一覧",  admins_genres_path %>
          </div>
          <div class="customer-header-nav">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
          </div>
        <% else %>
          <div class="customer-header-nav">
            <%= link_to "About", "#" %>
          </div>
          <div class="customer-header-nav">
            <%= link_to "商品一覧", items_path %>
          </div>
          <div class="customer-header-nav">
            <%= link_to "新規登録", new_customer_registration_path %>
          </div>
          <div class="customer-header-nav">
            <%= link_to "ログイン", new_customer_session_path %>
          </div>
        <% end %>
      </div>
      </header>
    <div class ="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>